[build]
  command = "yarn build"
  publish = "public/build"
  functions = "functions/"

[dev]
  command = "yarn dev"
  framework = "#custom"
  port = 3031
  targetPort = 5000
  functions = "functions/"
