[build]
  command = "yarn build"
  functions = "functions"
  publish = "dist"

[dev]
  command = "yarn dev"
  functions = "functions"
  framework = "#custom"
  targetPort = 5000
  port = 3031

[[redirects]]
  from = "/plants"
  to = "/.netlify/functions/get-plants-page-for-user"
  status = 200

[[redirects]]
  from = "/results"
  to = "/.netlify/functions/get-results-page"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  force = false
  status = 404
