[build]
  command = "yarn build"
  publish = "public"
  functions = "functions/"

[dev]
  command = "yarn dev"
  framework = "#custom"
  port = 3031
  targetPort = 5000
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
