name: Continuous tests

env:
  TREFLE_API_TOKEN: ${{ secrets.TREFLE_API_TOKEN }}
  TREFLE_BASE_URL: ${{ secrets.TREFLE_BASE_URL }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Cache node_modules: https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install
      - run: yarn test:unit

  test-e2e:
    name: E2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev:netlify
          wait-on: 'http://localhost:3031'
