name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test:unit
  e2e-tests:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v1.16.1
        with:
          browser: chrome
